### ISSUE TITLE
Unable to build bpm when compiling with address-model=64

### ISSUE THREAD

**Issue by eldiener** [boostorg/bpm#2]
When building a 64-bit version of bpm a compiler error because 

`sizeof( state_ ) >= sizeof( CLzmaDec )`

 is false in line 28 of lzma_reader.cpp:

`typedef char assert_large_enough[ sizeof( state_ ) >= sizeof( CLzmaDec )? 1: -1 ];`

Is this intended to fail for 64-bit compilation ? Using mingw-w64/gcc-9.2 the message in 64-bit compilation the message is:

```
..\src\lzma_reader.cpp:28:85: error: narrowing conversion of '-1' from 'int' to 'long long unsigned int' [-Wnarrowing]
   28 |     typedef char assert_large_enough[ sizeof( state_ ) >= sizeof( CLzmaDec )? 1: -1 ];
      |                                                                                     ^
..\src\lzma_reader.cpp:28:77: error: size '-1' of array 'assert_large_enough' is negative
   28 |     typedef char assert_large_enough[ sizeof( state_ ) >= sizeof( CLzmaDec )? 1: -1 ];
      |                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~

```

while with msvc-14.2 in 64-bit compilation the message is:

```
lzma_reader.cpp
..\src\lzma_reader.cpp(28): error C2118: negative subscript

```

Doing a 32-bit compilation succeeds in both cases. Is bpm designed to only work as a 32-bit application ?

**Comment by pdimov** [comment]
What is `sizeof( CLzmaDec )` on 64 bit? We just need to adjust the size of `state_` to be big enough.

**Comment by eldiener** [comment]
Fixed by PR
